import 'package:ytanim/video_model.dart';

const sampleVideos = [
  Video(
    id: 1,
    thumbnail: 'assets/thumbs/birthday.jpg',
    src: 'assets/videos/birthday.mp4',
    title: 'Birthday',
    published: '15 hours ago',
    views: '204k views',
    duration: '11:46',
  ),
  Video(
    id: 2,
    thumbnail: 'assets/thumbs/boxing1.jpg',
    src: 'assets/videos/boxing1.mp4',
    title: 'Boxing 1',
    published: '2 hours ago',
    views: '192k views',
    duration: '4:39',
  ),
  Video(
    id: 3,
    thumbnail: 'assets/thumbs/boxing2.jpg',
    src: 'assets/videos/boxing2.mp4',
    title: 'World Class Boxer training for the Championship title next week',
    published: '6 hours ago',
    views: '58.3k views',
    duration: '2:33',
  ),
  Video(
    id: 4,
    thumbnail: 'assets/thumbs/flower.jpg',
    src: 'assets/videos/flower.mp4',
    title: 'Flower',
    published: '11 hours ago',
    views: '92.4k views',
    duration: '12:65',
  ),
  Video(
    id: 5,
    thumbnail: 'assets/thumbs/skipping.jpg',
    src: 'assets/videos/skipping.mp4',
    title: 'Skipping',
    published: '20 hours ago',
    views: '2.3M views',
    duration: '1:04',
  ),
  Video(
    id: 6,
    thumbnail: 'assets/thumbs/walking.jpg',
    src: 'assets/videos/walking.mp4',
    title: 'Walking',
    published: '14 hours ago',
    views: '20.8k views',
    duration: '9:01',
  ),
  Video(
    id: 7,
    thumbnail: 'assets/thumbs/workman.jpg',
    src: 'assets/videos/workman.mp4',
    title: 'Workman',
    published: '15 hours ago',
    views: '11.6k views',
    duration: '14:83',
  ),
];
